#!/usr/bin/Rscript

# ------------------------------------------------------------------------------
# 
# Author: Gabriele Girelli
# Email: gigi.ga90@gmail.com
# Version: 0.0.1
# Description: plot Z distribution generated by findoof.py
# 
# ------------------------------------------------------------------------------



# DEPENDENCIES =================================================================

suppressMessages(library(argparser))
library(ggplot2)

# INPUT ========================================================================

# Create arguent parser
parser = arg_parser('Plot Z distribution generated by findoof.py',
	name = 'zplot.R')

# Define mandatory arguments
parser = add_argument(parser, arg = 'intable',
	help = 'Path to input intensity table generated by findoof.py')
parser = add_argument(parser, arg = 'outpdf',
	help = 'Path to output pdf.')

# Parse arguments
p = parse_args(parser)

# Attach argument values to variables
attach(p['' != names(p)])

# FUNCTIONS ====================================================================

plotZ = function(fin) {
	t = read.delim(fin, header = F, as.is = T)
	colnames(t) = c("file", "z", "sumI")

	p = ggplot(t, aes(x = z, y = sumI, color = file)) + geom_line()
	p = p + ggtitle(paste0(fin, " - Intensity sum over Z"))
	p = p + guides(color = guide_legend(title = "Field of View"))
	p = p + xlab("Slice index") + ylab("Intensity sum [a.u.]")
	print(p)
}

# RUN ==========================================================================

pdf(outpdf, width = 18, height = 8)

plotZ(intable)

graphics.off()

# END --------------------------------------------------------------------------

################################################################################
